### PR TITLE
Add color to JSON keys

### PR DESCRIPTION
**Pull request by SimonDegraeve**

### CODE REVIEW

**Comment by voronianski** [comment]
@SimonDegraeve could you also provide a screenshot?

**Comment by SimonDegraeve** [comment]
JSON keys with color

**Comment by voronianski** [comment]
@SimonDegraeve sorry, I'm not sure that I would like to merge this.. Looks like too much colors and inconsistent color with datatypes (keys are strings -> strings are green), in my opinion it's better to use tabulation to differentiate nested levels. 

Though I'm open to discussion maybe it's worth including this as an optional functionality.

**Comment by SimonDegraeve** [comment]
I agree with you on the "too much colors" for the screenshot in my comment, it was too show all the levels. The image I included in the `/screenshots` folder is what it looks like in real-world case.

I guess this kind of features is matter of taste. So I don't mind if it is optional.

**Comment by tomatau** [comment]
I kind of like this PR, I'm often using objects with strings as both keys and values.. it makes a whole lot'a green! 

Personally I would like to see all object keys be white and I can justify this reasoning.

For me, a string key is not really the same type as a string value.
e.g.
```
ob1 = {
 key: "value",
 num: 1
}
ob2 = {
 "key": "value",
 "num: 1
}
console.log(ob1, ob2)
```

Currently, the key changes colour from green to blue if the value is a function defined on the object or changes to white if it's a function shorthand, but stays the same colour for strings, variables, numbers, regex... To me, this feels inconsistent.

I'd like to see all keys just blue or white as purple is used a lot already for many key words.

White for keys seems more suitable for me, as that's the colour of variables.

**Comment by voronianski** [comment]
@SimonDegraeve closing this as I won't add such functionality for now.

**Comment by voronianski** [comment]
@SimonDegraeve after testing I've changed my mind and added your code (https://github.com/voronianski/oceanic-next-color-scheme/commit/69c3db92f003db123c1ebc6c2c07a61e25a3e7b8) to the new version of theme, it appeared to be quite useful, thanks!

**Pull request closed without merging**
